Repository escape-capstone-design/Server, pull requests merged in 2023-11, with the labels that each got.

#3 [FEAT] ChatGPT를 통한 FeedBack 도출 기능 추가
  .gitignore
  main.py
  service/feedback.py
Labels: 기능 추가

#4 [FEAT] 파인 튜닝 모델을 활용한 채점 기능 추가
  .gitignore
  main.py
  schema/grade_schema.py
  service/feedback.py
  service/grade.py
Labels: 기능 추가

#6 [CHORE] requirements.txt로 패키지 관리
  requirements.txt
Labels: chore

#12 [FIX] 변경된 채점 기준 적용
  service/grade.py
Labels: 수정

#17 [REFACTOR] 채점 시 코사인 유사도 값도 함께 반환
  service/grade.py
Labels: 리팩토링
